--==============================================================
-- DBMS name:      IBM DB2 Version 10 for z/OS
-- Created on:     2018/10/16 10:52:14
--==============================================================


--ALTER TABLE MDMP_ATTATCHMENT
--   DROP FOREIGN KEY PF_CMT_ATMT;
--
--ALTER TABLE MDMP_COLLECTION
--   DROP FOREIGN KEY PF_CATE_COLL;
--
--ALTER TABLE MDMP_COLLECTION_CATEGORY
--   DROP FOREIGN KEY PF_CATE_SELF;
--
--ALTER TABLE MDMP_META_COMMENT
--   DROP FOREIGN KEY PF_CMT_BOARD;
--
--ALTER TABLE MDMP_META_COMMENT
--   DROP FOREIGN KEY PF_CMT_SELF;
--
--DROP TABLE MDMP_ATTATCHMENT;
--
--DROP TABLE MDMP_BOARD;
--
--DROP TABLE MDMP_COLLECTION;
--
--DROP TABLE MDMP_COLLECTION_CATEGORY;
--
--DROP TABLE MDMP_META_COMMENT;
--
--DROP TABLE MDMP_META_STATISTICS;

--DROP TABLE MDMP_TRACKER;

--DROP TABLE MDMP_FREQUENT_KEYWORD;

--==============================================================
-- Table: MDMP_ATTATCHMENT
--==============================================================
CREATE TABLE MDMP_ATTATCHMENT (
   ATTACHMENT_ID        VARCHAR(32)            NOT NULL,
   COMMENT_ID           VARCHAR(32),
   URL                  VARCHAR(256),
   ATTACHMENT_NAME      VARCHAR(256),
   CONSTRAINT P_IDENTIFIER_1 PRIMARY KEY (ATTACHMENT_ID)
);

COMMENT ON TABLE MDMP_ATTATCHMENT IS
'附件';

COMMENT ON COLUMN MDMP_ATTATCHMENT.ATTACHMENT_ID IS
'附件ID';

COMMENT ON COLUMN MDMP_ATTATCHMENT.COMMENT_ID IS
'评论ID';

COMMENT ON COLUMN MDMP_ATTATCHMENT.URL IS
'url';

COMMENT ON COLUMN MDMP_ATTATCHMENT.ATTACHMENT_NAME IS
'附件名';

--==============================================================
-- Table: MDMP_BOARD
--==============================================================
CREATE TABLE MDMP_BOARD (
   BOARD_ID             VARCHAR(32)            NOT NULL,
   BOARD_NAME           VARCHAR(32),
   MODERATOR            VARCHAR(32),
   CONSTRAINT P_IDENTIFIER_1 PRIMARY KEY (BOARD_ID)
);

COMMENT ON TABLE MDMP_BOARD IS
'版块';

COMMENT ON COLUMN MDMP_BOARD.BOARD_ID IS
'版块ID';

COMMENT ON COLUMN MDMP_BOARD.BOARD_NAME IS
'版块名';

COMMENT ON COLUMN MDMP_BOARD.MODERATOR IS
'版主';

--==============================================================
-- Table: MDMP_COLLECTION
--==============================================================
CREATE TABLE MDMP_COLLECTION (
   COLLECTION_ID        VARCHAR(32)            NOT NULL,
   CATEGORY_ID          VARCHAR(32),
   COLLECTION_TYPE      VARCHAR(32),
   COLLECTION_VALUE     VARCHAR(32),
   COLLECTION_NAME      VARCHAR(256),
   OWNER                VARCHAR(32),
   GMT_COLLECTION       TIMESTAMP,
   CONSTRAINT P_IDENTIFIER_1 PRIMARY KEY (COLLECTION_ID)
);

COMMENT ON TABLE MDMP_COLLECTION IS
'收藏';

COMMENT ON COLUMN MDMP_COLLECTION.COLLECTION_ID IS
'收藏ID';

COMMENT ON COLUMN MDMP_COLLECTION.CATEGORY_ID IS
'分类ID';

COMMENT ON COLUMN MDMP_COLLECTION.COLLECTION_TYPE IS
'收藏类型';

COMMENT ON COLUMN MDMP_COLLECTION.COLLECTION_VALUE IS
'收藏值';

COMMENT ON COLUMN MDMP_COLLECTION.COLLECTION_NAME IS
'收藏名';

COMMENT ON COLUMN MDMP_COLLECTION.OWNER IS
'拥有者';

COMMENT ON COLUMN MDMP_COLLECTION.GMT_COLLECTION IS
'收藏时间';

--==============================================================
-- Table: MDMP_COLLECTION_CATEGORY
--==============================================================
CREATE TABLE MDMP_COLLECTION_CATEGORY (
   CATEGORY_ID          VARCHAR(32)            NOT NULL,
   PARENT_CATEGORY_ID   VARCHAR(32),
   CATEGORY_NAME        VARCHAR(32),
   CONSTRAINT P_IDENTIFIER_1 PRIMARY KEY (CATEGORY_ID)
);

COMMENT ON TABLE MDMP_COLLECTION_CATEGORY IS
'收藏分类';

COMMENT ON COLUMN MDMP_COLLECTION_CATEGORY.CATEGORY_ID IS
'分类ID';

COMMENT ON COLUMN MDMP_COLLECTION_CATEGORY.PARENT_CATEGORY_ID IS
'父ID';

COMMENT ON COLUMN MDMP_COLLECTION_CATEGORY.CATEGORY_NAME IS
'分类名';

--==============================================================
-- Table: MDMP_META_COMMENT
--==============================================================
CREATE TABLE MDMP_META_COMMENT (
   COMMENT_ID           VARCHAR(32)            NOT NULL,
   TARGET_COMMENT_ID    VARCHAR(32),
   BOARD_ID             VARCHAR(32),
   FINGERPRINT          VARCHAR(32),
   META_ATTR            VARCHAR(256),
   RATING               INTEGER,
   TITLE                VARCHAR(256),
   CONTENT              VARCHAR(4000),
   DISCUSSANT           VARCHAR(32),
   GMT_COMMENT          TIMESTAMP,
   STATUS               VARCHAR(32),
   COMMENT_TYPE         VARCHAR(32),
   TAG                  VARCHAR(256),
   STICKY               DEC(1),
   VISITS               INTEGER,
   REPLY_COUNT          INTEGER,
   CONSTRAINT P_IDENTIFIER_1 PRIMARY KEY (COMMENT_ID)
);

COMMENT ON TABLE MDMP_META_COMMENT IS
'评论';

COMMENT ON COLUMN MDMP_META_COMMENT.COMMENT_ID IS
'评论ID';

COMMENT ON COLUMN MDMP_META_COMMENT.TARGET_COMMENT_ID IS
'目标评论ID';

COMMENT ON COLUMN MDMP_META_COMMENT.BOARD_ID IS
'版块ID';

COMMENT ON COLUMN MDMP_META_COMMENT.FINGERPRINT IS
'指纹';

COMMENT ON COLUMN MDMP_META_COMMENT.META_ATTR IS
'属性名';

COMMENT ON COLUMN MDMP_META_COMMENT.RATING IS
'评分';

COMMENT ON COLUMN MDMP_META_COMMENT.TITLE IS
'标题';

COMMENT ON COLUMN MDMP_META_COMMENT.CONTENT IS
'内容';

COMMENT ON COLUMN MDMP_META_COMMENT.DISCUSSANT IS
'评论者';

COMMENT ON COLUMN MDMP_META_COMMENT.GMT_COMMENT IS
'评论时间';

COMMENT ON COLUMN MDMP_META_COMMENT.STATUS IS
'状态';

COMMENT ON COLUMN MDMP_META_COMMENT.COMMENT_TYPE IS
'评论类型';

COMMENT ON COLUMN MDMP_META_COMMENT.TAG IS
'标签';

COMMENT ON COLUMN MDMP_META_COMMENT.STICKY IS
'置顶';

COMMENT ON COLUMN MDMP_META_COMMENT.VISITS IS
'访问量';

COMMENT ON COLUMN MDMP_META_COMMENT.REPLY_COUNT IS
'回帖数';

--==============================================================
-- Table: MDMP_META_STATISTICS
--==============================================================
CREATE TABLE MDMP_META_STATISTICS (
   STATISTICS_ID        VARCHAR(32)            NOT NULL,
   FINGERPRINT          VARCHAR(32),
   VISITS               INTEGER,
   COMMENT_COUNT        INTEGER,
   FINAL_RATING         DEC(8, 2),
   CONSTRAINT P_IDENTIFIER_1 PRIMARY KEY (STATISTICS_ID)
);

COMMENT ON TABLE MDMP_META_STATISTICS IS
'元数据统计数据';

COMMENT ON COLUMN MDMP_META_STATISTICS.STATISTICS_ID IS
'统计ID';

COMMENT ON COLUMN MDMP_META_STATISTICS.FINGERPRINT IS
'指纹';

COMMENT ON COLUMN MDMP_META_STATISTICS.VISITS IS
'访问量';

COMMENT ON COLUMN MDMP_META_STATISTICS.COMMENT_COUNT IS
'评论量';

COMMENT ON COLUMN MDMP_META_STATISTICS.FINAL_RATING IS
'最终分';

ALTER TABLE MDMP_ATTATCHMENT
   ADD CONSTRAINT PF_CMT_ATMT FOREIGN KEY (COMMENT_ID)
      REFERENCES MDMP_META_COMMENT (COMMENT_ID)
      ON DELETE RESTRICT;

ALTER TABLE MDMP_COLLECTION
   ADD CONSTRAINT PF_CATE_COLL FOREIGN KEY (CATEGORY_ID)
      REFERENCES MDMP_COLLECTION_CATEGORY (CATEGORY_ID)
      ON DELETE RESTRICT;

ALTER TABLE MDMP_COLLECTION_CATEGORY
   ADD CONSTRAINT PF_CATE_SELF FOREIGN KEY (PARENT_CATEGORY_ID)
      REFERENCES MDMP_COLLECTION_CATEGORY (CATEGORY_ID)
      ON DELETE RESTRICT;

ALTER TABLE MDMP_META_COMMENT
   ADD CONSTRAINT PF_CMT_BOARD FOREIGN KEY (BOARD_ID)
      REFERENCES MDMP_BOARD (BOARD_ID)
      ON DELETE RESTRICT;

ALTER TABLE MDMP_META_COMMENT
   ADD CONSTRAINT PF_CMT_SELF FOREIGN KEY (TARGET_COMMENT_ID)
      REFERENCES MDMP_META_COMMENT (COMMENT_ID)
      ON DELETE RESTRICT;

--==============================================================
-- MDMP_META_COMMENT增加驳回原因字段
--==============================================================     
ALTER TABLE MDMP_META_COMMENT
   ADD REASON VARCHAR(4000);

COMMENT ON COLUMN MDMP_META_COMMENT.REASON IS
'驳回原因';

--==============================================================
-- MDMP_META_COMMENT增加是否已解决字段
--==============================================================
ALTER TABLE MDMP_META_COMMENT
   ADD SOLVED DEC(1);

COMMENT ON COLUMN MDMP_META_COMMENT.SOLVED IS
'是否已解决';

--==============================================================
-- MDMP_META_COMMENT增加更新时间字段
--==============================================================
ALTER TABLE MDMP_META_COMMENT
   ADD GMT_UPDATE TIMESTAMP;

COMMENT ON COLUMN MDMP_META_COMMENT.GMT_UPDATE IS
'更新时间';

--==============================================================
-- MDMP_COLLECTION_CATEGORY增加拥有者字段
--==============================================================
ALTER TABLE MDMP_COLLECTION_CATEGORY
   ADD OWNER VARCHAR(32);

COMMENT ON COLUMN MDMP_COLLECTION_CATEGORY.OWNER IS
'拥有者';

--==============================================================
-- Table: MDMP_TRACKER
--==============================================================
CREATE TABLE MDMP_TRACKER (
   TRACKER_ID           VARCHAR(32)            NOT NULL,
   FINGERPRINT          VARCHAR(32),
   OWNER                VARCHAR(32),
   GMT_VIEW             TIMESTAMP,
   CONSTRAINT P_IDENTIFIER_1 PRIMARY KEY (TRACKER_ID)
);

COMMENT ON TABLE MDMP_TRACKER IS
'足迹';

COMMENT ON COLUMN MDMP_TRACKER.TRACKER_ID IS
'足迹ID';

COMMENT ON COLUMN MDMP_TRACKER.FINGERPRINT IS
'指纹';

COMMENT ON COLUMN MDMP_TRACKER.OWNER IS
'拥有者';

COMMENT ON COLUMN MDMP_TRACKER.GMT_VIEW IS
'查看时间';

--==============================================================
-- Table: MDMP_FREQUENT_KEYWORD
--==============================================================
CREATE TABLE MDMP_FREQUENT_KEYWORD (
   KEYWORD_ID           VARCHAR(32)            NOT NULL,
   KEYWORD              VARCHAR(256),
   COUNT                INTEGER,
   CONSTRAINT P_IDENTIFIER_1 PRIMARY KEY (KEYWORD_ID)
);

COMMENT ON TABLE MDMP_FREQUENT_KEYWORD IS
'常用搜索词';

COMMENT ON COLUMN MDMP_FREQUENT_KEYWORD.KEYWORD_ID IS
'关键词ID';

COMMENT ON COLUMN MDMP_FREQUENT_KEYWORD.KEYWORD IS
'关键词';

COMMENT ON COLUMN MDMP_FREQUENT_KEYWORD.COUNT IS
'次数';